### PR TITLE
added functionality to move the cards if there is an empty stack in the deck

### PR DESCRIPTION
**Pull request by jrotithor**

### CODE REVIEW

**Comment by matsuish** [comment]
This is just my opinion.
 Move function may be called from acesUp class (because acesUp class represents game itself), so it should not assume to get acesUp object as an argument.  Instead, you may be able to write like "Move_card(Card c, int r, Card[ ][ ] board)" and assume that it is called from acesUp class with its member valuable "Card[ ][ ] board."
And also, when moving cards, I think inputting card suit and number is not necessary, because with "Card[ ][ ] board" (which contains all cards on the board) and two integers, which represent columns a player wants to move from/to, you can get the Card information you want to move from/to. The card information can be found from "Card[ ][ ] board" if row and column are provided, and the row a player is going to move from/to can be automatically decided because the row must be the top of the Cards in each column. It can be found like this

```
for(int i=0; i<board[column].length; i++) 
    if(board[column][i] == null) topRow = i-1;    //if it is -1, it means no card on the column
```

So the arguments of move function may look like Move_card(Card[ ][ ] board, int col1, int col2). These argument may be able to be received in acesUp class by some way.

My sentence must be messy. please ignore if it does not make sense.

**Comment by jrotithor** [comment]
Thank you. These are all very good points.
The reason that I chose to put move_card in its own class is that I wanted to try to implement the move functionality by affecting the rest of the gameplay as little as possible. You are correct in that it could be put into the Aces_up class,and it would be a very good design choice that would not negatively affect implementation at all. Also, the card suit and number are not necessary to gameplay, but I included them in there to make the game more beginner-friendly and to guide them through how to play.
Hope I made sense and answered your questions.

**Comment by matsuish** [comment]
User friendliness was a new point of view for me. It is very nice to consider users!
thank you for answering my message.

**Comment by danielgwj** [comment]
looks good guys, and yea I do agree with Shotaro on this, it would be a real hassle to always have to reference from another class during the game itself.

**Pull request merged**
